Add support for modernc.org/sqlite
golang-migrate/migrate pull request #555
Opened 2021-04-30 22:27 UTC by gammazero

This PR adds support for the CGo-free port of SQLite.

Reference issue #59

2021-04-30 23:03 UTC, dhui requested changes
Looks like there's limited support for OS and arches: https://pkg.go.dev/modernc.org/sqlite#hdr-Changelog

How has compatibility with sqlite been ensured/tested with this db driver?

I don't think we can replace the old sqlite db driver with this one yet, but we can add it as a new one, similar to how we [support both pgx and pq](https://github.com/golang-migrate/migrate/pull/517).

2021-05-04 19:45 UTC, gammazero commented
@dhui Yes, OS/arch support is currently limited, so I have removed sqlite from the `DATABASE` build target in the `Makefile`.  This makes its support equivalent to how sqlite3 is supported.  Users can build the GUI with support for sqlite if needed, but support is not built by default and is not included in the binary distribution.

I think that go-migrate should support both sqlite and sqlite3 as both are popular packages, and this PR does not intend to replace [sqlite3](https://github.com/mattn/go-sqlite3), but offer [sqlite](https://pkg.go.dev/modernc.org/sqlite) support in addition. 

This PR is basically a copy of the `database/sqlite3` package, but using the modernc.org sqlite instead.

2021-05-05 17:04 UTC, dhui approved these changes

2021-05-05 17:04 UTC, merged

2021-12-18 04:48 UTC, dhui commented
Here's an updated link of supported OSes and Arches: https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures