Update README.md
golang-migrate/migrate pull request #602
Opened 2021-07-27 20:14 UTC by nd-sin

2021-07-28 16:12 UTC, dhui commented
`migrate` exists as a CLI and library. We already have [install instructions](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#installation) for the CLI and [examples](https://github.com/golang-migrate/migrate#use-in-your-go-project) of how to use it as a library. Please make the documentation improvement in the proper section.

2021-08-17 14:02 UTC, obalunenko requested changes

2021-08-17 14:02 UTC, obalunenko commented on README.md
> +`go get github.com/golang-migrate/migrate/v4`
Check https://github.com/golang-migrate/migrate/tree/master/cmd/migrate and https://github.com/golang-migrate/migrate#use-in-your-go-project
This update of Readme is redundant

2021-08-18 16:59 UTC, dhui commented
Agreed with @obalunenko, this PR is unnecessary

2021-08-18 16:59 UTC, closed without merging