ci: migrate from CircleCI to GitHub Actions
golang-migrate/migrate pull request #605
Opened 2021-08-04 07:43 UTC by Juneezee

Completely migrates from CircleCI to GitHub Actions. Runs `lint` and `test` on every push and pull request.

2021-08-04 08:21 UTC, Fontinalis reviewed
I do like the idea of having everything in GitHub Actions and remove CircleCI from the list of tools we use and it's a great PR to replace tests on commits and PRs! 👍🏻 

@dhui Thoughts?

2021-08-04 17:05 UTC, dhui requested changes
Thanks for the PR and helping us improve our release process @Juneezee !

@Fontinalis 
> I do like the idea of having everything in GitHub Actions and remove CircleCI from the list of tools we use and it's a great PR to replace tests on commits and PRs! 👍🏻
> 
> @dhui Thoughts?

Agreed, we should move our tests to use GitHub Actions as well.
Let's keep the other CI and docker files for now in case we need to continue using them. We can clean them up later.

2021-08-04 17:05 UTC, dhui commented on .github/workflows/ci.yaml
> +        go: ["1.15", "1.16"]
Use `["1.15.x", "1.16.x"]`

2021-08-04 17:35 UTC, Fontinalis commented on .github/workflows/ci.yaml
> +name: CI
Personally I would prefer to keep it separate, but that could be just my taste.

2021-08-04 17:55 UTC, dhui commented on .github/workflows/ci.yaml
> +name: CI
Let's leave them separate for now then

2021-08-05 17:02 UTC, dhui requested changes
Add [`workflow_run`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run) to the GoReleaser workflow/job (`.github/workflows/release.yaml`) so that it only runs after tests pass

2021-08-05 17:25 UTC, Juneezee commented
> Add [`workflow_run`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run) to the GoReleaser workflow/job (`.github/workflows/release.yaml`) so that it only runs after tests pass

@dhui There is a caveat if we use [`workflow_run`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run) to trigger the `goreleaser` job, as described in [this StackOverflow answer](https://stackoverflow.com/a/68078768/7902371).

If the `goreleaser` job is trigerred by `workflow_run` instead of `on: push: tags: "v*"`, GoReleaser would not be able to detect tag that is pushed, which would then cause the job to fail.

2021-08-05 17:30 UTC, Fontinalis commented
> If the goreleaser job is trigerred by workflow_run instead of on: push: tags: "v*", GoReleaser would not be able to detect tag that is pushed, which would then cause the job to fail.

On the other hand, this could be solved if we merge the two workflows into one, and use the following code by @Juneezee  to check if the release should run or not 

```diff
  goreleaser:
    name: Release a new version
    environment: GoReleaser
    runs-on: ubuntu-latest
+   needs: [lint, test]
+   if: ${{ success() && github.repository == 'golang-migrate/migrate' && contains(github.ref, 'refs/tags/v') }}
    ...
```

So I'm happy to turn my vote on the question of "should we merge the two workflows or not".

2021-08-05 18:14 UTC, Fontinalis approved these changes
Looks legit to me! @dhui you concur?

2021-08-05 18:38 UTC, Juneezee commented on .github/workflows/ci.yaml
> +        with:
I missed these lines in the previous commit. They are required for coveralls to work correctly with parallel tests, see https://github.com/shogo82148/actions-goveralls#parallel-job-example

2021-08-05 18:40 UTC, Juneezee commented
Last round of review I think, everything seems to be well configured :rocket:

2021-08-05 21:18 UTC, dhui requested changes

2021-08-05 21:18 UTC, dhui commented on .github/workflows/ci.yaml
> +  test-finish:
~Rename to `send-coverage` and add a human-readable `name: Send coverage`~

EDIT: This looks like a duplicate sending of coverage?

2021-08-05 21:18 UTC, dhui commented on .github/workflows/ci.yaml
> +    if: ${{ success() && github.repository == 'golang-migrate/migrate' && contains(github.ref, 'refs/tags/v') }}
Use `startsWith()` instead of `contains()`

2021-08-05 23:26 UTC, dhui commented on .github/workflows/ci.yaml
> +  test-finish:
Oh, NVM, it looks like this notifies github that coverage has pass. Let's name this `check-coverage` with a human readable `name: Check coverage`

2021-08-06 00:14 UTC, Juneezee commented
@dhui Please take a look again :smiley:

2021-08-06 04:11 UTC, dhui approved these changes
Thanks for migrating our tests over!

2021-08-06 04:12 UTC, merged