Use DELETE FROM instead of TRUNCATE for MySQL
golang-migrate/migrate pull request #656
Opened 2021-11-17 19:34 UTC by antigremlin

Resolves issue #584 

In MySQL, TRUNCATE statements cannot be rolled back, at least for 5.7:
- https://dev.mysql.com/doc/refman/5.7/en/truncate-table.html
- https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

This is another attempt at fixing, as the previous PR #585 has stalled. The credit goes to @martinarrieta

2021-11-17 19:37 UTC, antigremlin commented
The first PR mentioned above accidentally rearranged imports. This PR only changes the one line necessary. I'd be happy to see this merged soon as this is a critical bug. It nearly did damage to one of my databases.

2021-12-07 22:37 UTC, dhui requested changes
Per https://github.com/golang-migrate/migrate/issues/584#issuecomment-867146738, the transaction needs to be serializable

2021-12-07 23:27 UTC, antigremlin commented
> Per [#584 (comment)](https://github.com/golang-migrate/migrate/issues/584#issuecomment-867146738), the transaction needs to be serializable

This PR fixes a very dangerous bug: If the migration process gets killed at the wrong moment, it leaves the version table empty (the truncate was successful, but the insert was interrupted). Next thing that happens is that the tool tries to reapply all the migrations from the beginning, which can be disastrous.  

I can mark it as serializable. But why do you think it changes anything? According to https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html `serializable` only affects SELECT statements, not DELETE and INSERT ones.

2021-12-08 05:25 UTC, dhui commented
> I can mark it as serializable. But why do you think it changes anything? According to https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html `serializable` only affects SELECT statements, not DELETE and INSERT ones.

Please do. For safety, we should use the most strict isolation level. There's nearly no downside and setting the migration version doesn't need to be performant. e.g. we're happy to pay for any overhead between `REPEATABLE READ` and `SERIALIZABLE` for the extra safety.
This protects against other instances of `migrate` reading the migration version, which may later update the version.

2021-12-16 16:53 UTC, obalunenko commented
@antigremlin Can you rebase your branch on base branch and update the PR? 🙏🏿

2021-12-18 04:21 UTC, dhui approved these changes

2021-12-18 04:21 UTC, merged

2021-12-23 22:27 UTC, antigremlin commented
> @antigremlin Can you rebase your branch on base branch and update the PR? 🙏🏿

My apologies. Was going to do that and didn't notice the PR is already merged.
Great to see this in. Thank you @dhui!